# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
