# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_sell_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
