# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='buy_it_now',
            field=models.IntegerField(default=0),
        ),
    ]
