# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_sell_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
