# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_auto_20161126_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='sell',
            name='choice',
            field=models.CharField(choices=[('1', 'Locomotive'), ('2', 'Engine'), ('3', 'Track'), ('4', 'Catalogue'), ('4', 'All')], default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='bid',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.Sell'),
        ),
    ]
