# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_auto_20161129_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sell.Sell'),
        ),
    ]
